TARGET = test-net
SRC    = test-net.c\
	net.c\
	../net-packets/net-packets.c\
	../node-tables/node-tables.c\
	../print/print.c\
	../cksum/cksum.c\
	../link-state/link-state.c\
	#../harry/transport.c\
	../harry/app.c\
	../shared/uart/uart.c\
	../shared/buffer8/buffer.c

-include ../Makefile.in
