TARGET = test-cksum
SRC    = test-cksum.c\
	cksum.c\
	../core/net.c\
	../print/print.c\
	../node-tables/node-tables.c\
	../net-packets/net-packets.c\
	../link-state/link-state.c

-include ../Makefile.in
