TARGET = test-packets
SRC    = test-packets.c\
	net-packets.c\
	../core/net.c\
	../print/print.c\
 	../cksum/cksum.c\
	 ../node-tables/node-tables.c\
	../link-state/link-state.c

-include ../Makefile.in
